updates:
  - commit-message:
      include: scope
      prefix: core
    directory: /
    package-ecosystem: npm
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: ci
    directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
version: 2
