labels:
  - color: D73A4A
    name: bug
    description: Something isn't working
  - color: 0366D6
    name: dependencies
    description: Pull requests or issues that related to dependencies
  - color: 0075CA
    name: documentation
    description: Improvements or additions to documentation
  - color: CFD3D7
    name: duplicate
    description: This issue or pull request already exists
  - color: A2EEEF
    name: enhancement
    description: Improvements or additions to an existing feature
  - color: 0E8A16
    name: feature
    description: New feature or request
  - color: 000000
    name: github_actions
    description: Pull requests that update GitHub Actions code
  - color: E99695
    name: help wanted
    description: Extra attention is needed
  - color: FFFFFF
    name: invalid
    description: This doesn't seem right
  - color: D876E3
    name: question
    description: Information or discussion requested
  - color: B60205
    name: security
    description: Security related fixes, enhancements, or improvements
  - color: 7057FF
    name: test
    description: Test related fixes, enhancements, or improvements
  - color: FBCA04
    name: wip
    description: Work in progress
  - color: FFFFFF
    name: wontfix
    description: This will not be worked on
