extends:
  - '@commitlint/config-conventional'
help: |
  **Possible types**:
  `ci`:       Changes to CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs).
  `core`:     Changes build processes, tooling, dependencies or general project structure.
  `doc`:      Adds or alters documentation.
  `feat`:     Adds a new feature.
  `fix`:      Solves a bug.
  `perf`:     Improves performance.
  `refactor`: Rewrites code without feature, performance or bug related changes.
  `revert`:   Changes that reverting other changes.
  `style`:    Improves formatting, white-space, etc.
  `test`:     Adds or modifies tests.
  `wip`:      Work in progress (temporary commits, which will eventually be rebased or otherwise removed).
rules:
  body-max-line-length: [1, 'always', 72]
  header-max-length: [1, 'always', 50]
  subject-case: [1, 'always', 'sentence-case']
  type-enum:
    - 2
    - always
    - - ci
      - core
      - doc
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
      - wip
