$schema: https://json.schemastore.org/prettierrc
attributeSort: ASC
plugins:
  - prettier-plugin-organize-attributes
  - prettier-plugin-organize-imports
printWidth: 100
semi: false
singleAttributePerLine: true
singleQuote: true
tabWidth: 2
trailingComma: es5
