dictionaries:
  - markdown
dictionaryDefinitions: []
language: en,en_GB
ignorePaths:
  - .*
  - '*.svg'
  - .gitignore
  - .vscode/**
  - dist/**
  - node_modules/**
  - pnpm-lock.yaml
ignoreWords:
  - anticsrf
  - argjson
  - elif
  - esac
  - fontawesome
  - Fonticons
  - Grantez
  - headlessui
  - inputmask
  - JSPCA
  - Jspca
  - jspca
  - JSPCA's
  - jspdf
  - lintstagedrc
  - lionels
  - lionelslegacyjersey
  - Lucida
  - Mansalva
  - mktemp
  - navpanes
  - pdfobject
  - predeploy
  - realpath
  - substr
  - svgrepo
  - Unhead
  - unhead
  - vueuse
  - wdth
  - webform
  - wght
import: []
version: 0.2
words: []
