dictionaries:
  - markdown
dictionaryDefinitions: []
language: en,en_GB
ignorePaths:
  - .*
  - '*.svg'
  - .gitignore
  - .vscode/**
  - dist/**
  - node_modules/**
  - pnpm-lock.yaml
ignoreWords:
  - anticsrf
  - argjson
  - commitlintrc
  - creativecommons
  - elif
  - esac
  - fontawesome
  - Fonticons
  - Grantez
  - headlessui
  - inputmask
  - JSPCA
  - JSPCA's
  - lionels
  - lionelslegacyjersey
  - Lucida
  - Mansalva
  - mktemp
  - predeploy
  - Prerender
  - prerender
  - prerenderer
  - prerendering
  - realpath
  - sublicensable
  - substr
  - svgrepo
  - Unhead
  - unhead
  - vueuse
  - waivable
  - webform
import: []
version: 0.2
words: []
