dictionaries:
  - markdown
dictionaryDefinitions: []
language: en,en_GB
ignorePaths:
  - .*
  - .gitignore
  - .vscode/**
  - dist/**
  - node_modules/**
  - pnpm-lock.yaml
ignoreWords:
  - argjson
  - elif
  - esac
  - lintstagedrc
  - lionels
  - mktemp
  - realpath
  - stylelint
  - substr
  - vueuse
import: []
version: 0.2
words: []
