blank_issues_enabled: true
contact_links:
  - about: Please do NOT use this email to post issues or feature requests.
    name: Send an e-mail to the developer
    url: mailto:info@lionelslegacyjersey.com
