name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: Build the project
        env:
          VITE_GTM_ID: ${{ secrets.GTM_ID }}
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
